sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gnakatani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gnakatani/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'docker'
  env: 'Docker-env-1'
  bucket_name: 'elasticbeanstalk-us-west-1-669505063135'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
